### ISSUE TITLE
No main?

### ISSUE THREAD

**Issue by jsprenkle** [ccressent/acnav#1]
python newb here. Shouldn't there be a main() somewhere in this code?
I'd like to extract height data from my archived file.

**Comment by jsprenkle** [comment]
explanation of python use of main() here:  https://stackoverflow.com/questions/22492162/understanding-the-main-method-of-python

**Comment by ccressent** [comment]
No `main()` because this is not a standalone program. It is a library to be used in your own project (or, like I did at the time, use interactively in a Python REPL).

Also note that I haven't touched it in 10+ years and the library is far from complete. I think you should be able to extract a height map with it though. Good luck!

**Comment by jsprenkle** [comment]
Thx Cyril. In my searches I stumbled on ACViewer. A stand alone app in C# (which I have much more experience with). They have a lot of documentation on the portal and cell file contents available too.
